server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host-name: localhost
    port-number: 6379
  cloud:
    gateway:
      routes:
        - id: book
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: reader
          uri: lb://reader-service
          predicates:
            - Path=/api/readers/**
        - id: subscription
          uri: lb://subscription-service
          predicates:
            - Path=/api/subscriptions/**
        - id: subscriptionplan
          uri: lb://subscription-plan-service
          predicates:
            - Path=/api/subscriptionplans/**
        - id: loan
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true


