server:
  port: 8001

spring:
  application:
    name: book-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projet_microservice
    username: postgres
    password: Douldoul1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
